{% set name = "pydruid" %}
{% set version = "0.5.9" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "78728bf5d7a313de609387445562a906806746f0b38b3fe8150226d09d9208e6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - pydruid = pydruid.console:main
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - pytest-runner

  run:
    - python
    - six >=1.9.0
    - requests
    - pandas
    - tornado
    - sqlalchemy
    - pygments
    - prompt_toolkit <2.0.0
    - tabulate

test:
  imports:
    - pydruid
    - pydruid.utils

about:
  home: https://github.com/druid-io/pydruid
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: A Python connector for Druid.
  dev_url: https://github.com/druid-io/pydruid
  doc_url: https://pythonhosted.org/pydruid/

extra:
  recipe-maintainers:
    - pmlandwehr
