{% set name = "pydruid" %}
{% set version = "0.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30b6efa722234183239296bf8e6d41aba7eea0eec3d68233ce6c413986864fea

build:
  noarch: python
  entry_points:
    - pydruid = pydruid.console:main
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner

  run:
    - python >=3.6
    - six >=1.9.0
    - requests
    - pandas
    - tornado
    - sqlalchemy
    - pygments
    - prompt_toolkit >=2.0.0
    - tabulate

test:
  imports:
    - pydruid
    - pydruid.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/druid-io/pydruid
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: A Python connector for Druid.
  dev_url: https://github.com/druid-io/pydruid
  doc_url: https://pythonhosted.org/pydruid/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
