{% set name = "pydruid" %}
{% set version = "0.5.7" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "88d4fa608c96969dc8f8e03cc0cfc4a38c4c3039b4f899db0af896ab0fa6ff23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  entry_points:
    - pydruid = pydruid.console:main
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - pip
    - pytest-runner

  run:
    - python >=3.6
    - six >=1.9.0
    - requests
    - pandas
    - tornado
    - sqlalchemy
    - pygments
    - prompt_toolkit <2.0.0
    - tabulate

test:
  imports:
    - pydruid
    - pydruid.utils

about:
  home: https://github.com/druid-io/pydruid
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: 'A Python connector for Druid.'
  dev_url: https://github.com/druid-io/pydruid
  doc_url: https://pythonhosted.org/pydruid/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
